import type { Metadata } from "next";
import "./globals.css";
import { spaceGrotesk } from "./fonts";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-light text-dark dark:bg-dark dark:text-light ${spaceGrotesk.className}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
